/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.IDS.FidelityProgram;



import it.unicam.cs.IDS.FireBase.FireBaseInitializer;
import org.checkerframework.checker.units.qual.A;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }


    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());
       Address prova = new Address("Via giulia piccolomini cicarelli",92,"62032","Camerino","Italy","Macerata");

    }

}
