/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.IDS.FidelityProgram;

import org.json.simple.parser.ParseException;
import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() throws IOException, ParseException {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
